### ISSUE TITLE
Unable to use the syntax highlighting for Universal Robots script

### ISSUE THREAD

**Issue by mochr** [RoboDK/Industrial-Robots-VSCode#1]
When I try to change the syntax highlighting for a .script file to Universal Robots, a "def" in the program gets highlighted but then Visual Studio Code freezes. After some time I get the message "The window is no longer responding", with the option to reopen, keep waiting or close.

Visual Studio Code version details:
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by SpongePatti** [comment]
I have a similar problem. Universal Robots-Script code won't be highlighted. In the feature contributions-list is under the supported languages a wrong file-extension (.pdl) for universal robots... Could this be changed?

**Comment by vdm-dev** [comment]
> When I try to change the syntax highlighting for a .script file to Universal Robots, a "def" in the program gets highlighted but then Visual Studio Code freezes.

I cannot reproduce the problem.
Could you please share your .script file?
I have tested on three different versions of VSCodium, as well as on VS Code.

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by RoboDK** [comment]
This extension and RoboDK were updated to the latest version with support for URScript syntax highlighting
