### ISSUE TITLE
What is the license for this repo?

### ISSUE THREAD

**Issue by ianathompson** [RoboDK/Industrial-Robots-VSCode#2]
You have provided this code on a public repo, but have not listed any information about the license.

- Is this open source?

- Is this GPL, LGPL, APGL? 

- What are the requirements for forking this project?

Please clarify this in the REPO so others can utilize it.

**Comment by RoboDK** [comment]
Thank you for noticing. 
The license is MIT, we just added the license file.

**Comment by ianathompson** [comment]
Cool. Thanks.
Helps clarify for forks and future project use.
