### ISSUE TITLE
Review Possibility of removing RoboDK branding from this app

### ISSUE THREAD

**Issue by ianathompson** [RoboDK/Industrial-Robots-VSCode#3]
I understand that this was developed by the RoboDK team, and has been included within the VSCodium app that is provided within the RoboDK installer.

Since the license is MIT and anyone can reuse and relicense and bundle in their software, it runs the risk of everyone trying to generate their own software package and increasing the number of extensions on the VS CODE Extension marketplace.

Do you think it might be possible to try to de-brand this product, and open it up to the greater community so that everyone can participate in the development of this tool?

Robot Manufacturers and other OLP software providers are less likely (possibly not at all) to participate if it is branded and copyrighted by RoboDK. I enjoy using this app. I want to recommend it to people, I want to contribute, but I cannot do so with the RoboDK name on it.

I am thinking of the better good for the world robot programming community, and I hope this is something you might consider.

**Comment by Phillip-May** [comment]
The code is pretty RoboDK agnostic, if your talking about the description page on the VSCode Marketplace, we can make it more generic, what changes would you like to see? If it's integrating a new language we can also help you.
