### ISSUE TITLE
VSCode Functionlist on ABB Rapid

### ISSUE THREAD

**Issue by do1kbl** [RoboDK/Industrial-Robots-VSCode#4]
I find your plugin for VSCode, It works perfect with ABB Rapid for me.

But its possible to see on the left corner the function of the rapid programm to jump directly to there like UltraEdit?

Good job
Kim

**Comment by vdm-dev** [comment]
Could you please attach a screenshot with the desired feature?

**Comment by sambertrdk** [comment]
Hi Kim, thank you for your feedback!
Function list is not in our current road map, but we will keep it in mind!
