### ISSUE TITLE
ABB snippet syntax for multi-select option doesn't work

### ISSUE THREAD

**Issue by K3PO-PCBD** [RoboDK/Industrial-Robots-VSCode#6]
## Expected Behavior
When a multi-select option is available in the snippet, the option should be highlighted and a drop down list appears to indicate which options are valid.

## Current Behavior
Currently the option list is displayed along with the braces and pipes, like so:
`ConfJ {|\On,\Off|};`
The field is not highlighted and must be manually edited to produce the correct syntax, like so:
`ConfJ \On;`
or
`ConfJ \Off;`

## Possible Solution
Change the code so that, in a multi-select field, the "$" is outside the braces.

## Steps to Reproduce
1. Edit or create a new file.mod and type "confj", select the snippet and press return.
2. 
![image](https://user-images.githubusercontent.com/51171802/170044665-37370d9a-5229-4281-b352-0cf3aa3b5bb9.png)

## Context (Environment)
Editing an ABB RAPID Module

## Detailed Description
Left brace should be between the "$"and position number to enable the correct behavior. i.e. Drop down list should appear when selecting the snippet.
Fix:
`    "ConfJ": {
        "prefix": "ConfJ",
        "body": [
            "ConfJ ${1|\\On,\\Off|};"
        ],
        "description": "Configuration flag On/Off (MoveL)"
    }
    ,`
Results in:
![image](https://user-images.githubusercontent.com/51171802/170042500-d7ecc9da-fc08-4b0d-9362-cbb21d33b102.png)

**Comment by sambertrdk** [comment]
@Phillip-May

**Comment by K3PO-PCBD** [comment]
After posting the original issue, I noticed that it's only 2 functions where the $ is in the wrong place. The others are all correct. So, basically just a typo in two places, CONFJ and CONFL (going from memory on the 2nd one)

**Comment by vdm-dev** [comment]
Thank you for describing the problem and the solution in so much detail.
